spring.application.name=digimenu



spring.datasource.url=jdbc:postgresql://db.dgzddotpywecesoolrlt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=BFellas2025!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.application.name=digimenu

# ===============================
# Database configuration (Railway)
# ===============================
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ===============================
# Hikari (important for Supabase)
# ===============================
spring.datasource.hikari.maximum-pool-size=3
spring.datasource.hikari.minimum-idle=1
spring.datasource.hikari.connection-timeout=30000

server.port=${PORT:8080}