spring.application.name=digimenu



spring.datasource.url=jdbc:postgresql://db.dgzddotpywecesoolrlt.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=BFellas2025!
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
